[log]
logDir = "./log"
logFile = "signaling"
# DEBUG INFO WARNING ERROR FATAL
# FATAL 请慎用，会导致进程退出
logLevel = "DEBUG"
logToStderr = true

[http]
port=8080
staticDir="./static"
staticPrefix="/static/"

[https]
port=8081
cert="./conf/cert.pem"
key="./conf/key.pem"

[xrpc]
connectTimeout=100
readTimeout=500
writeTimeout=500
server="127.0.0.1:9000,127.0.0.1:9000"


